### ISSUE TITLE
PortRT can not run in spongeforge-1.10.2-2171-5.1.0-BETA-2010

### ISSUE THREAD

**Issue by Firemonkey08** [Maxqia/PoreRT#16]
Try to load the plugin the first time and I get this following error.
Have I to use another Spongeforgeversion?

[08:21:35] [Server thread/TRACE] [sponge/sponge]: Sending event FMLServerStartingEvent to mod sponge
[08:21:35] [Server thread/ERROR] [Sponge/sponge]: Could not pass FMLServerStartingEvent to Plugin{id=pore, name=PoreRT, version=1.0.0-SNAPSHOT, description=A Bukkit-Sponge Porting Layer, source=C:\Program Files (x86)\MC Plug-In\Server_Forge_2\mods\PoreRT-1.0.0-SNAPSHOT.jar}
java.lang.NullPointerException
	at blue.lapis.pore.Pore.onStarting(Pore.java:137) ~[Pore.class:1.0.0-SNAPSHOT]
	at blue.lapis.pore.launch.PoreBootstrap.onStarting(PoreBootstrap.java:92) ~[PoreBootstrap.class:1.0.0-SNAPSHOT]
	at org.spongepowered.common.event.listener.GameStartingServerEventListener_PoreBootstrap_onStarting4.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2171-5.1.0-BETA-2010]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301) [SpongeModEventManager.class:1.10.2-2171-5.1.0-BETA-2010]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330) [SpongeModEventManager.class:1.10.2-2171-5.1.0-BETA-2010]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:229) [SpongeMod.class:1.10.2-2171-5.1.0-BETA-2010]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:52) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:845) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:292) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:293) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[08:21:35] [Server thread/TRACE] [sponge/sponge]: Sent event FMLServerStartingEvent to mod sponge

**Comment by Maxqia** [comment]
I don't support 1.10 atm, you can use the old version here : https://github.com/Maxqia/PoreRT/tree/api5
