### ISSUE TITLE
Residence Reloaded Error

### ISSUE THREAD

**Issue by lofivo** [Maxqia/PoreRT#30]
Sponge 1.10.2-2202-5.1.0-BETA-2086
problem:
1.Permission can't work,I have tried PermissionManager,PermissionEx.
2.Error Log:

> [Server thread/ERROR] [pore/]: Could not pass event PoreEntityChangeBlockEvent to Residence v4.5.13.3
> org.bukkit.event.EventException
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[JavaPluginLoader$1.class:1.0.0-backport]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.0.0-backport]
> 	at blue.lapis.pore.event.SpongeEventHandler.call(SpongeEventHandler.java:110) ~[SpongeEventHandler.class:1.0.0-backport]
> 	at blue.lapis.pore.event.SpongeEventHandler.handle(SpongeEventHandler.java:98) ~[SpongeEventHandler.class:1.0.0-backport]
> 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2202-5.1.0-BETA-2086]
> 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2086]
> 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:285) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2086]
> 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2086]
> 	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2086]
> 	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141) ~[SpongeImpl.class:1.10.2-2202-5.1.0-BETA-2086]
> 	at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:619) ~[TrackingUtil.class:1.10.2-2202-5.1.0-BETA-2086]
> 	at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:539) ~[TrackingUtil.class:1.10.2-2202-5.1.0-BETA-2086]
> 	at org.spongepowered.common.event.tracking.phase.tick.EntityTickPhaseState.lambda$processPostTick$5(EntityTickPhaseState.java:223) ~[EntityTickPhaseState.class:1.10.2-2202-5.1.0-BETA-2086]
> 	at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57) [CapturedSupplier.class:1.10.2-2202-5.1.0-BETA-2086]
> 	at org.spongepowered.common.event.tracking.phase.tick.EntityTickPhaseState.processPostTick(EntityTickPhaseState.java:223) [EntityTickPhaseState.class:1.10.2-2202-5.1.0-BETA-2086]
> 	at org.spongepowered.common.event.tracking.phase.tick.TickPhase.unwind(TickPhase.java:68) [TickPhase.class:1.10.2-2202-5.1.0-BETA-2086]
> 	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:192) [CauseTracker.class:1.10.2-2202-5.1.0-BETA-2086]
> 	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:154) [TrackingUtil.class:1.10.2-2202-5.1.0-BETA-2086]
> 	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zjm000(WorldServer.java:2757) [ls.class:?]
> 	at net.minecraft.world.World.func_72866_a(World.java:4071) [aid.class:?]
> 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) [ls.class:?]
> 	at net.minecraft.world.World.func_72870_g(World.java:1934) [aid.class:?]
> 	at net.minecraft.world.World.func_72939_s(World.java:5723) [aid.class:?]
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2122) [ls.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
> Caused by: java.lang.UnsupportedOperationException: SpongeEntityType{id=pixelmon:chattingnpc, name=chattingnpc, translation=SpongeTranslation{id=entity.generic.name}, modid=pixelmon, class=com.pixelmonmod.pixelmon.entities.npcs.NPCChatting}
> 	at blue.lapis.pore.converter.type.TypeConverter.checkDefined(TypeConverter.java:47) ~[TypeConverter.class:1.0.0-backport]
> 	at blue.lapis.pore.converter.type.TypeConverter.doBackward(TypeConverter.java:65) ~[TypeConverter.class:1.0.0-backport]
> 	at com.google.common.base.Converter.correctedDoBackward(Converter.java:164) ~[minecraft_server.1.10.2.jar:?]
> 	at com.google.common.base.Converter$ReverseConverter.correctedDoForward(Converter.java:244) ~[minecraft_server.1.10.2.jar:?]
> 	at com.google.common.base.Converter.convert(Converter.java:147) ~[minecraft_server.1.10.2.jar:?]
> 	at blue.lapis.pore.converter.type.entity.EntityConverter.of(EntityConverter.java:125) ~[EntityConverter.class:1.0.0-backport]
> 	at blue.lapis.pore.impl.event.entity.PoreEntityChangeBlockEvent.getEntityType(PoreEntityChangeBlockEvent.java:79) ~[PoreEntityChangeBlockEvent.class:1.0.0-backport]
> 	at com.bekvon.bukkit.residence.listeners.ResidenceBlockListener.onBlockFall(ResidenceBlockListener.java:246) ~[?:?]
> 	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source) ~[?:?]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[JavaPluginLoader$1.class:1.0.0-backport]
> 	... 28 more

**Comment by Maxqia** [comment]
1. I don't support 1.10
2. I don't recommend using any protection plugins because most of the events aren't implemented (so some protections might not work)
Anyways patch incoming for modded entities (only for 1.11 though) :P
Permissions should already be fixed in 1.11
